### ISSUE TITLE
Disabling past date

### ISSUE THREAD

**Issue by andreipot** [pushtell/react-bootstrap-date-picker#30] opened 2016-08-31 22:20 UTC
how can we disable past dates? don't we have minDate prop?

**Comment by wehriam** [comment] 2016-08-31 22:31
Min and max dates are not currently supported. Closing as a duplicate of #18.

**Closed by wehriam** 2016-08-31 22:31 UTC

**Comment by andreipot** [comment] 2016-08-31 22:41
@wehriam  when can we expect that?

**Comment by wehriam** [comment] 2016-08-31 22:45
This project does not have a roadmap and there is no timeline for this feature. 

Let me know if you would like to discuss professional support options.
